# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: hackermention
runtime: python39

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --workers 1 --threads 10 --timeout 6000 -b :$PORT app:app

automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .9
  min_pending_latency: 100ms
  max_concurrent_requests: 30

inbound_services:
- warmup

handlers:
- url: .*
  script: auto
  secure: always
